# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=24)),
                ('author_dob', models.DateField(default=datetime.date(2018, 4, 15), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('user_defined_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('aD', 'Dimension'), ('aM', 'Measure')], max_length=11)),
            ],
        ),
    ]
