# Generated by Django 2.0.4 on 2018-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
