# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180415_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_dob',
            field=models.DateField(default=2018, null=True),
        ),
    ]
