# Generated by Django 2.0.4 on 2018-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_configuration_is_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_key',
            field=models.NullBooleanField(),
        ),
    ]
