# Generated by Django 2.0.4 on 2018-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20180416_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('aD', 'aD'), ('aM', 'aM')], max_length=11),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
