# Generated by Django 2.0.4 on 2018-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20180417_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('aD', 'Dimension'), ('aM', 'Measure')], max_length=11),
        ),
    ]
