# Generated by Django 2.0.4 on 2018-04-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20180425_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Name', unique=True),
        ),
    ]
