# Generated by Django 2.0.4 on 2018-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_auto_20180425_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
