# Generated by Django 2.0.4 on 2018-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_configuration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='is_kpi',
            field=models.BooleanField(default=True),
        ),
    ]
