# Generated by Django 2.0.4 on 2018-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_auto_20180426_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='is_kpi',
            field=models.BooleanField(default=False),
        ),
    ]
