# Generated by Django 2.0.5 on 2018-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_auto_20180426_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, null=True)),
                ('f_description', models.TextField(null=True)),
            ],
        ),
    ]
