# Generated by Django 2.0.5 on 2018-05-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula',
            old_name='f_description',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='formula',
            old_name='f_name',
            new_name='name',
        ),
    ]
